"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/__main__.py']
DATA_FILES = []
OPTIONS = {}

setup(
    name="Windesheim2ICS",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'], install_requires=['ics', 'mako']
)
